#pragma once 

#include "INode.h"
#include "CClass.h"
#include "CProgram.h"
#include "CClass.h"
#include "CClassSequence.h"
#include "CId.h"
#include "CMain.h"
#include "CMethod.h"
#include "CMethodSequence.h"
#include "CStatementSequence.h"
#include "CExpressionSequence.h"
#include "CVar.h"
#include "CVarSequence.h"
#include "IExpression.h"
#include "IStatement.h"
#include "IType.h"

#include "CallExpression.h"
#include "ArrayExpression.h"
#include "AsterExpression.h"
#include "LowerExpression.h"
#include "MinusExpression.h"
#include "PlusExpression.h"
#include "AndExpression.h"
#include "NewArrayExpression.h"
#include "NotExpression.h"
#include "ParenExpression.h"
#include "NewExpression.h"
#include "LengthExpression.h"
#include "IdExpression.h"
#include "IntegerExpression.h"
#include "BoolExpression.h"
#include "ThisExpression.h"

#include "WhileStatement.h"
#include "PrintStatement.h"
#include "IfElseStatement.h"
#include "BracedSequenceStatement.h"
#include "AssignStatement.h"
#include "ArrayAssignStatement.h"

#include "BoolType.h"
#include "ClassType.h"
#include "IntArrayType.h"
#include "IntType.h"

namespace AST {}